"""empty message

Revision ID: 1b9633e0e128
Revises: 5293ed30788e
Create Date: 2021-05-01 16:03:04.074678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9633e0e128'
down_revision = '5293ed30788e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('latest_version', sa.String(length=25), nullable=True))
    op.alter_column('device', 'version',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=25),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'version',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('device', 'latest_version')
    # ### end Alembic commands ###
