"""empty message

Revision ID: 2283fb6e67b1
Revises: 8507cda5085c
Create Date: 2021-05-05 20:59:04.745044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2283fb6e67b1'
down_revision = '8507cda5085c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('device_group_id_fkey', 'device', type_='foreignkey')
    op.create_foreign_key(None, 'device', 'group', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.create_foreign_key('device_group_id_fkey', 'device', 'group', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
