"""empty message

Revision ID: 4bf0fe4fea35
Revises: f80246091fcd
Create Date: 2021-05-13 19:13:27.715910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf0fe4fea35'
down_revision = 'f80246091fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring', sa.Column('cpu_temp', sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitoring', 'cpu_temp')
    # ### end Alembic commands ###
