"""empty message

Revision ID: 5293ed30788e
Revises: 950bee344977
Create Date: 2021-04-30 22:49:42.099488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5293ed30788e'
down_revision = '950bee344977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('ip', sa.String(length=20), nullable=True))
    op.drop_column('task', 'sequence_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('sequence_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('device', 'ip')
    # ### end Alembic commands ###
