"""empty message

Revision ID: 950bee344977
Revises: e1612c42a720
Create Date: 2021-04-11 23:32:21.620355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950bee344977'
down_revision = 'e1612c42a720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('device', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('monitoring', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('monitoring', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('package', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('package', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('task', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('task', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'updated_at')
    op.drop_column('task', 'created_at')
    op.drop_column('package', 'updated_at')
    op.drop_column('package', 'created_at')
    op.drop_column('monitoring', 'updated_at')
    op.drop_column('monitoring', 'created_at')
    op.drop_column('device', 'updated_at')
    op.drop_column('device', 'created_at')
    # ### end Alembic commands ###
