"""empty message

Revision ID: c8acdc95e881
Revises: d80dcae78afc
Create Date: 2021-03-09 18:39:33.906592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8acdc95e881'
down_revision = 'd80dcae78afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('cpu_usage', sa.DECIMAL(), nullable=True),
    sa.Column('ram_usage', sa.DECIMAL(), nullable=True),
    sa.Column('disk_space', sa.DECIMAL(), nullable=True),
    sa.Column('used_disk_space', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitoring')
    # ### end Alembic commands ###
