"""empty message

Revision ID: d2c8d9dd5dda
Revises: e3f2f29f86ab
Create Date: 2021-05-01 16:10:13.791801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c8d9dd5dda'
down_revision = 'e3f2f29f86ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('package', 'latest_version',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('package', 'latest_version',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=25),
               existing_nullable=True)
    # ### end Alembic commands ###
