"""empty message

Revision ID: d9e2d7126f33
Revises: fbfbb357547c
Create Date: 2021-05-07 21:35:28.202336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9e2d7126f33'
down_revision = 'fbfbb357547c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('state', sa.String(length=20), nullable=True))
    op.add_column('task', sa.Column('task_message', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'task_message')
    op.drop_column('task', 'state')
    # ### end Alembic commands ###
