"""empty message

Revision ID: e1612c42a720
Revises: c8acdc95e881
Create Date: 2021-03-26 14:32:47.215713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1612c42a720'
down_revision = 'c8acdc95e881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('app', sa.String(length=50), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=25), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('message', sa.String(length=100), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
