"""empty message

Revision ID: e3f2f29f86ab
Revises: 1b9633e0e128
Create Date: 2021-05-01 16:04:29.684221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f2f29f86ab'
down_revision = '1b9633e0e128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'latest_version')
    op.add_column('package', sa.Column('latest_version', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package', 'latest_version')
    op.add_column('device', sa.Column('latest_version', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
